# Generated by Django 2.0.2 on 2019-06-22 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoFruVer', models.CharField(choices=[('palta', 'palta'), ('damasco', 'damasco'), ('piña', 'piña'), ('arándano', 'arándano'), ('arándano (rojo)', 'arándano (rojo)'), ('plátano', 'plátano'), ('guinda', 'guinda'), ('ciruela', 'ciruela'), ('coco', 'coco'), ('frambuesa', 'frambuesa'), ('frutilla', 'frutilla'), ('fresa', 'fresa'), ('cereza', 'cereza'), ('granada', 'granada'), ('higo', 'higo'), ('kiwi', 'kiwi'), ('lima', 'lima'), ('limón', 'limón'), ('mandarina', 'mandarina'), ('mango', 'mango'), ('manzana', 'manzana'), ('maracuyá', 'maracuyá'), ('durazno', 'durazno'), ('melón', 'melón'), ('membrillo', 'membrillo'), ('mora', 'mora'), ('naranja', 'naranja'), ('nectarina', 'nectarina'), ('papaya', 'papaya'), ('pera', 'pera'), ('pomelo', 'pomelo'), ('sandía', 'sandía'), ('uva', 'uva'), (' zarzamora', ' zarzamora'), ('acelga', 'acelga'), ('ajo', 'ajo'), ('alcachofa', 'alcachofa'), ('alcaucil', 'alcaucil'), ('apio', 'apio'), ('arveja', 'arveja'), ('batata', 'batata'), ('berenjena', 'berenjena'), ('betarraga', 'betarraga'), ('brócoli', 'brócoli'), ('zapallo', 'zapallo'), ('camote', 'camote'), ('cebolla', 'cebolla'), ('champiñón', 'champiñón'), ('choclo', 'choclo'), ('repollo', 'repollo'), ('coles de Bruselas', 'coles de Bruselas'), ('zapallo italiano', 'zapallo italiano'), ('coliflor', 'coliflor'), ('maíz', 'maíz'), ('espárrago', 'espárrago'), ('espinaca', 'espinaca'), ('frijol', 'frijol'), ('guisante', 'guisante'), ('jitomate', 'jitomate'), ('poroto', 'poroto'), ('lechuga', 'lechuga'), ('repollo morado', 'repollo morado'), ('papa', 'papa'), ('pepino', 'pepino'), ('pimentón', 'pimentón'), ('pimiento', 'pimiento'), ('puerro', 'puerro'), ('rábano', 'rábano'), ('remolacha', 'remolacha'), ('seta', 'seta'), ('tomate', 'tomate'), ('zanahoria', 'zanahoria')], default='papa', max_length=50)),
                ('FotoProducto', models.FileField(upload_to='projects')),
                ('NombreProducto', models.CharField(max_length=50)),
                ('CantidadKG', models.IntegerField()),
                ('Precio', models.IntegerField()),
                ('Latitud', models.CharField(max_length=50)),
                ('Longitud', models.CharField(max_length=50)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
