# Generated by Django 2.0.2 on 2019-06-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190622_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='UsuarioName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
