# Generated by Django 2.0.7 on 2019-07-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_registro_usuarioname'),
    ]

    operations = [
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproducto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('vendedor', models.CharField(max_length=200)),
                ('comprador', models.CharField(max_length=200)),
            ],
        ),
    ]
