# Generated by Django 2.0.7 on 2019-07-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarjetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idusuario', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('mesvencimiento', models.IntegerField()),
                ('añovencimiento', models.IntegerField()),
                ('cvc', models.IntegerField()),
            ],
        ),
    ]
