# Generated by Django 2.0.7 on 2019-07-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_tarjetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetas',
            name='tipotarjeta',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='añovencimiento',
            field=models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2018', max_length=9999),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='cvc',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='mesvencimiento',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=99),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='numero',
            field=models.CharField(max_length=16),
        ),
    ]
