# Generated by Django 2.0.7 on 2019-07-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20190709_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipopago',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
