# Generated by Django 2.0.7 on 2019-07-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20190709_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='tipotarjeta',
            field=models.CharField(choices=[('Santander', 'Banco Santander'), ('Banco BBVA', 'Banco BBVA'), ('Banco de Chile', 'Banco de Chile'), ('BancoEstado', 'BancoEstado'), ('Banco Scotiabank', 'Banco Scotiabank'), ('Banco Itau', 'Banco Itau'), ('Banco Falabella', 'Banco Falabella'), ('Visa', 'Visa'), ('Mastercard', 'Mastercard')], default='Santander', max_length=50),
        ),
    ]
